//  There are twoi phases in the js durin the excution 


// Memory Creation Phase 

//  In this phase memory is created for the variables 

//  And second one is the xecution phase 



//  At first whatever the code is it is executed in in global enviorment 
//  And this allocated to the this method


// and then second phase is Memory Execution Phase 

//  In this phase at first all the variables are assigend the undefined 

//  Third Phase is the Execuion phase 